# Your Solution
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
      - name: book-catalog
        image: pamtask72contreg.azurecr.io/book-catalog:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "8080"
        - name: DATABASE_URL
          value: "postgresql://my_books_db_29ah_user:3AKu7PEqH0YHc983X2Dxt8nMtbsKPNaq@dpg-crij26e8ii6s73f4dq5g-a.oregon-postgres.render.com/my_books_db_29ah"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers: 
      - name: inventory-management
        image: pamtask72contreg.azurecr.io/inventory-management:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "8081"
        - name: DATABASE_URL
          value: "postgresql://my_books_db_29ah_user:3AKu7PEqH0YHc983X2Dxt8nMtbsKPNaq@dpg-crij26e8ii6s73f4dq5g-a.oregon-postgres.render.com/my_books_db_29ah"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081